Introduced gaps per monitor - resolved #74
nikitabobko/AeroSpace pull request #117
Opened 2024-01-14 20:09 UTC by wojciech-kulik

Resolved issue #74

Introduced new syntax for gaps:

```toml
# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:         outer-left = 8
# - Per monitor:      outer-left = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#   In this example, 24 is a default value when there is no match.

[gaps]
inner-horizontal = 10
inner-vertical = [{ monitor."main" = 1 }, { monitor."secondary" = 2 }, 5]
outer-left = 12
outer-bottom = [13]
outer-top = [{ monitor."built-in" = 3 }, { monitor."secondary" = 4 }, 6]
outer-right = [{ monitor.2 = 7 }]
```

Notes:
I tried to implement in an extensible way. I introduced `DynamicConfigValue<T>` that can be used to provide either constant value or an array of rules.

Currently, this type defines two possible values: `constant` and `perMonitor(rules, defaultValue)`. However, it could be extended in the future to support more conditions.

PS. I also fixed some Xcode warnings.

2024-01-14 22:45 UTC, wojciech-kulik commented
This PR introduces breaking changes. 
What should be done in this case? 
Do you assume that breaking changes can appear in the beta phase?

I guess the best approach would be to start releasing new versions regularly with appropriate release notes.

2024-01-15 18:31 UTC, nikitabobko requested changes

2024-01-15 20:04 UTC, wojciech-kulik commented on src/config/parseConfig.swift
> +        }
What should be returned then by the function?

2024-01-15 20:12 UTC, wojciech-kulik commented on src/config/parseConfig.swift
> +        if let error = rules.compactMap(\.errorOrNil).first {
What should I return if there are errors when my output is non-optional and non-`Result`?

2024-01-16 00:35 UTC, nikitabobko commented
Merged with the following patch:
```diff
diff --git a/LocalPackage/Sources/Common/util/SequenceEx.swift b/LocalPackage/Sources/Common/util/SequenceEx.swift
index 4ce8b24..8c231b1 100644
--- a/LocalPackage/Sources/Common/util/SequenceEx.swift
+++ b/LocalPackage/Sources/Common/util/SequenceEx.swift
@@ -15,6 +15,11 @@ public extension Sequence {
         return result
     }
 
+    var first: Element? {
+        var iter = makeIterator()
+        return iter.next()
+    }
+
     func mapAllOrFailure<T, E>(_ transform: (Self.Element) -> Result<T, E>) -> Result<[T], E> {
         var result: [T] = []
         for element in self {
diff --git a/docs/config-examples/default-config.toml b/docs/config-examples/default-config.toml
index e0422dd..5b4579f 100644
--- a/docs/config-examples/default-config.toml
+++ b/docs/config-examples/default-config.toml
@@ -34,26 +34,25 @@ default-root-container-layout = 'tiles'
 #               tall monitor (anything higher than wide) gets vertical orientation
 default-root-container-orientation = 'auto'
 
+# Gaps between windows (inner-*) and between monitor edges (outer-*).
+# Possible values:
+# - Constant:     gaps.outer.top = 8
+# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
+#                 In this example, 24 is a default value when there is no match.
+#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
+#                 See: https://nikitabobko.github.io/AeroSpace/guide.html#assign-workspaces-to-monitors
+gaps.inner.horizontal = 0
+gaps.inner.vertical =   0
+gaps.outer.left =       0
+gaps.outer.bottom =     0
+gaps.outer.top =        0
+gaps.outer.right =      0
+
 # Visual indent makes it easier to understand that containers of the same orientation are nested.
 # If you have 'enable-normalization-opposite-orientation-for-nested-containers' enabled then
 # there is no way to observe the indent
 indent-for-nested-containers-with-the-same-orientation = 30
 
-# Gaps between windows (inner-*) and between monitor edges (outer-*).
-# Possible values:
-# - Constant:         outer-left = 8
-# - Per monitor:      outer-left = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
-#   In this example, 24 is a default value when there is no match.
-#   Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
-#   See: https://nikitabobko.github.io/AeroSpace/guide.html#assign-workspaces-to-monitors
-[gaps]
-inner.horizontal = 0
-inner.vertical =   0
-outer.left =       0
-outer.bottom =     0
-outer.top =        0
-outer.right =      0
-
 # 'main' binding mode declaration
 # See: https://nikitabobko.github.io/AeroSpace/guide.html#binding-modes
 # 'main' binding mode must be always presented
diff --git a/src/config/parseConfig.swift b/src/config/parseConfig.swift
index 235b0fc..62fdac7 100644
--- a/src/config/parseConfig.swift
+++ b/src/config/parseConfig.swift
@@ -27,7 +27,7 @@ private func getConfigFileUrl() -> URL? {
         ?? FileManager.default.homeDirectoryForCurrentUser.appending(path: ".config/")
     let candidates = [
         FileManager.default.homeDirectoryForCurrentUser.appending(path: dotFileName),
-        xdgConfigHome.appending(path: "aerospace").appending(path: fileName)
+        xdgConfigHome.appending(path: "aerospace").appending(path: fileName),
     ]
     let existingCandidates: [URL] = candidates.filter { (candidate: URL) in FileManager.default.fileExists(atPath: candidate.path) }
     let count = existingCandidates.count
@@ -88,8 +88,8 @@ typealias ParsedToml<T> = Result<T, TomlParseError>
 
 extension ParserProtocol {
     func transformRawConfig(_ raw: S,
-        _ value: TOMLValueConvertible,
-        _ backtrace: TomlBacktrace,
+                            _ value: TOMLValueConvertible,
+                            _ backtrace: TomlBacktrace,
                             _ errors: inout [TomlParseError]) -> S {
         raw.copy(keyPath, parse(value, backtrace, &errors).getOrNil(appendErrorTo: &errors))
     }
@@ -244,78 +244,78 @@ func parseSimpleType<T>(_ raw: TOMLValueConvertible) -> T? {
 func parseDynamicValue<T>(
     _ raw: TOMLValueConvertible,
     _ valueType: T.Type,
-    _ initial: T,
+    _ fallback: T,
     _ backtrace: TomlBacktrace,
     _ errors: inout [TomlParseError]
 ) -> DynamicConfigValue<T> {
     if let simpleValue = parseSimpleType(raw) as T? {
         return .constant(simpleValue)
     } else if let array = raw.array {
-        guard !array.isEmpty else {
-            errors.append(.semantic(backtrace, "Array must not be empty"))
-            return .constant(initial)
+        if array.isEmpty {
+            errors.append(.semantic(backtrace, "The array must not be empty"))
+            return .constant(fallback)
         }
 
         guard let defaultValue = array.last.flatMap({ parseSimpleType($0) as T? }) else {
-            errors.append(.semantic(backtrace, "The last item must be a default value (type: \(T.self))"))
-            return .constant(initial)
+            errors.append(.semantic(backtrace, "The last item in the array must be of type \(T.self)"))
+            return .constant(fallback)
         }
 
-        let rules: [PerMonitorValue<T>] = parsePerMonitorValues(TOMLArray(array.dropLast()), backtrace, &errors)
-
-        guard !rules.isEmpty else {
-            errors.append(.semantic(backtrace, "Array must containt at least one monitor pattern"))
-            return .constant(initial)
+        if array.dropLast().isEmpty {
+            errors.append(.semantic(backtrace, "The array must contain at least one monitor pattern"))
+            return .constant(fallback)
         }
 
+        let rules: [PerMonitorValue<T>] = parsePerMonitorValues(TOMLArray(array.dropLast()), backtrace, &errors)
+
         return .perMonitor(rules, default: defaultValue)
     } else {
         errors.append(.semantic(backtrace, "Unsupported type: \(raw.type), expected: \(valueType) or array"))
-        return .constant(initial)
+        return .constant(fallback)
     }
 }
 
 func parsePerMonitorValues<T>(_ array: TOMLArray, _ backtrace: TomlBacktrace, _ errors: inout [TomlParseError]) -> [PerMonitorValue<T>] {
-    array.enumerated().compactMap { index, raw -> PerMonitorValue<T>? in
+    array.enumerated().compactMap { (index: Int, raw: TOMLValueConvertible) -> PerMonitorValue<T>? in
         var backtrace = backtrace + .index(index)
 
-        guard let tableItem = raw.table else {
-            errors.append(expectedActualTypeError(expected: .table, actual: raw.type, backtrace))
+        guard let (key, value) = raw.unwrapTableWithSingleKey(expectedKey: "monitor", &backtrace)
+            .flatMap({ $0.value.unwrapTableWithSingleKey(expectedKey: nil, &backtrace) })
+            .getOrNil(appendErrorTo: &errors) else {
             return nil
         }
 
-        guard tableItem.keys.count == 1 else {
-            errors.append(.semantic(backtrace, "Table must contain exactly one key with monitor table"))
-            return nil
-        }
-
-        guard let table = tableItem["monitor"]?.table else {
-            errors.append(.semantic(backtrace, "Missing monitor table"))
-            return nil
-        }
+        let monitorDescriptionResult = parseMonitorDescription(key, backtrace)
 
-        backtrace = backtrace + .key("monitor")
+        guard let monitorDescription = monitorDescriptionResult.getOrNil(appendErrorTo: &errors) else { return nil }
 
-        guard table.keys.count == 1 else {
-            errors.append(.semantic(backtrace, "Monitor table must contain exactly one key with monitor pattern"))
+        guard let value = parseSimpleType(value) as T? else {
+            errors.append(.semantic(backtrace, "Expected type is '\(T.self)'. But actual type is '\(value.type)'"))
             return nil
         }
 
-        return table.lazy.compactMap { key, value in
-            let backtrace = backtrace + .key(key)
-            let monitorDescr [...]

2024-01-16 00:36 UTC, nikitabobko commented
https://github.com/nikitabobko/AeroSpace/commit/377c35bbbe1febf3d89738e524d91cda11ca4a6f

2024-01-16 00:36 UTC, closed without merging

2024-01-16 00:56 UTC, wojciech-kulik commented
🍻 

PS. Out of curiosity, why don't you use pull requests to merge/push changes?