implement balance-sizes command
nikitabobko/AeroSpace pull request #290
Opened 2024-06-19 21:01 UTC by karadnik-flutterint

command sets the same size for all windows that share common parent

2024-06-19 21:46 UTC, nikitabobko requested changes
Thanks! A few comments need to be fixed. Mainly the documentation

2024-06-19 21:46 UTC, nikitabobko commented on Sources/Common/cmdArgs/other/CmdKind.swift
> +    case balanceSizes = "balance-sizes"
Entries in this enum are sorted alphabetically

2024-06-19 21:46 UTC, nikitabobko commented on Sources/AppBundle/command/BalanceSizesCommand.swift
> +struct BalanceSizesCommand: Command {
Please create the documentation `./docs/aerospace-balance-sizes.adoc`, `./docs/commands.adoc` and update `args-grammar.conf` (it's used for shell completion)

2024-06-19 21:46 UTC, nikitabobko commented on Sources/AppBundle/command/BalanceSizesCommand.swift
> +            if let child = child as? TilingContainer, !child.isEffectivelyEmpty {
`child.isEffectivelyEmpty` is redundant. Effectively empty containers are automatically removed before commands get called

2024-06-19 21:46 UTC, nikitabobko commented on Sources/AppBundleTests/command/BalanceSizesCommandTest.swift
> +                XCTAssertEqual(window.getWeight(workspace.rootTilingContainer.orientation), 1)
Indentation is incorrect

2024-06-19 21:46 UTC, nikitabobko commented on Sources/AppBundleTests/command/BalanceSizesCommandTest.swift
> +            }
Indentation is incorrect

2024-06-19 21:46 UTC, nikitabobko commented on Sources/AppBundle/command/other/parseCommand.swift
> +            case .balanceSizes:
case handling should be sorted alphabetically

2024-06-19 21:46 UTC, nikitabobko commented on Sources/Common/cmdArgs/other/parseCmdArgs.swift
> +            case .balanceSizes:
Entries handling should be sorted alphabetically

2024-06-19 21:46 UTC, nikitabobko commented on Sources/AppBundle/command/BalanceSizesCommand.swift
> +        if parent.layout != Layout.tiles { return }
You should skip `setWeight` for children of non-tiles containers (children of accordion containers), but you still should recursively check children of accordion containers

Example:
```
h_accordion
  window1
  v_tiles
    window2  <-- need to call setWeight for this leaf
    window3  <-- need to call setWeight for this leaf
```

2024-06-19 21:52 UTC, nikitabobko commented on Sources/AppBundle/command/BalanceSizesCommand.swift
> +struct BalanceSizesCommand: Command {
Please use `./build-docs.sh` to check how site and manpages look like after your changes (`./.man` and `./.site/commands.html`)

2024-06-20 07:42 UTC, karadnik-flutterint commented on Sources/AppBundle/command/BalanceSizesCommand.swift
> +        if parent.layout != Layout.tiles { return }
Oh, i tought accordion cannot have tiles. Will filx

2024-06-20 14:15 UTC, karadnik-flutterint commented
@nikitabobko, all comments should be addressed now.

this is how docs look like
<img width="801" alt="Screenshot 2024-06-20 at 17 11 38" src="https://github.com/nikitabobko/AeroSpace/assets/137300720/3b6cf84e-78dd-4ff4-a5e2-85ca0f50144e">

2024-06-25 23:16 UTC, closed without merging

2024-06-25 23:16 UTC, nikitabobko commented
Thanks!

Merged with the following patch:
```diff
diff --git a/Sources/AppBundle/command/BalanceSizesCommand.swift b/Sources/AppBundle/command/BalanceSizesCommand.swift
index d1d7c369..9456cdc2 100644
--- a/Sources/AppBundle/command/BalanceSizesCommand.swift
+++ b/Sources/AppBundle/command/BalanceSizesCommand.swift
@@ -3,7 +3,7 @@ import Common
 import Foundation
 
 struct BalanceSizesCommand: Command {
-    let args = BalanceSizesCmdArgs(rawArgs: [])
+    let args: BalanceSizesCmdArgs
 
     func _run(_ state: CommandMutableState, stdin: String) -> Bool {
         check(Thread.current.isMainThread)
@@ -12,9 +12,10 @@ struct BalanceSizesCommand: Command {
     }
 
     func balance(_ parent: TilingContainer) {
-        parent.children.forEach { child in
-            if parent.layout == .tiles {
-                child.setWeight(parent.orientation, 1)
+        for child in parent.children {
+            switch parent.layout {
+                case .tiles: child.setWeight(parent.orientation, 1)
+                case .accordion: break // Do nothing
             }
             if let child = child as? TilingContainer {
                 balance(child)
diff --git a/Sources/AppBundle/command/other/parseCommand.swift b/Sources/AppBundle/command/other/parseCommand.swift
index d58a88f9..41bdf8eb 100644
--- a/Sources/AppBundle/command/other/parseCommand.swift
+++ b/Sources/AppBundle/command/other/parseCommand.swift
@@ -20,7 +20,7 @@ extension CmdArgs {
         let command: any Command
         switch Self.info.kind {
             case .balanceSizes:
-                command = BalanceSizesCommand()
+                command = BalanceSizesCommand(args: self as! BalanceSizesCmdArgs)
             case .close:
                 command = CloseCommand(args: self as! CloseCmdArgs)
             case .closeAllWindowsButCurrent:
diff --git a/Sources/Cli/subcommandDescriptionsGenerated.swift b/Sources/Cli/subcommandDescriptionsGenerated.swift
index 335eb414..df36c278 100644
--- a/Sources/Cli/subcommandDescriptionsGenerated.swift
+++ b/Sources/Cli/subcommandDescriptionsGenerated.swift
@@ -1,5 +1,6 @@
 // FILE IS GENERATED BY generate.sh
 let subcommandDescriptions = [
+    ["  balance-sizes", "Balance sizes of all windows in the current workspace"],
     ["  close-all-windows-but-current", "On the focused workspace, close all windows but current"],
     ["  close", "Close the focused window"],
     ["  config", "Query AeroSpace config options"],
diff --git a/docs/aerospace-balance-sizes.adoc b/docs/aerospace-balance-sizes.adoc
index 3f49ee3b..41dbd4f8 100644
--- a/docs/aerospace-balance-sizes.adoc
+++ b/docs/aerospace-balance-sizes.adoc
@@ -2,24 +2,23 @@
 include::util/man-attributes.adoc[]
 :manname: aerospace-balance-sizes
 // tag::purpose[]
-:manpurpose: Balance the sizes of all opened windows in current workspace
+:manpurpose: Balance sizes of all windows in the current workspace
 // end::purpose[]
 
 == Synopsis
 // tag::synopsis[]
-aerospace balance-sizes [-h|--help] 
+aerospace balance-sizes [-h|--help]
 // end::synopsis[]
 
 == Description
-Balance the sizes of all opened windows in current workspace
 
 // tag::body[]
 {manpurpose}
 
+// end::body[]
+
 include::util/conditional-options-header.adoc[]
 
 -h, --help:: Print help
 
-// end::body[]
-
 include::util/man-footer.adoc[]
```