Add `--no-outer-gaps` to the `fullscreen` command
nikitabobko/AeroSpace pull request #472
Opened 2024-08-30 02:27 UTC by vrumger

Closes #373

2024-08-31 16:10 UTC, nikitabobko requested changes

2024-08-31 16:10 UTC, nikitabobko commented on Sources/AppBundle/model/MonitorEx.swift
> +    }
Unnecessary property. You can simply use `visibleRect`

2024-09-01 08:39 UTC, vrumger commented
thanks for the suggestions, I fixed all of them

2024-09-01 09:28 UTC, nikitabobko commented on Sources/Common/cmdArgs/FullscreenCmdArgs.swift
> +            USAGE: fullscreen [-h|--help] [--no-outer-gaps] [on|off]
1. You forgot to update synopsis in `.adoc`
2. You forgot to update the arguments parser to disallow invalid combination of `--no-outer-gaps` and `off` arguments. Please take a look at how invalid combinations of args are reported in other commands and do the same (e.g. `FocusCmdArgs`)

2024-09-01 09:34 UTC, nikitabobko commented on grammar/commands-bnf-grammar.txt
> +    | fullscreen [--no-outer-gaps] [on]
Shell completion should allow `on` and `--no-outer-gaps` in different order

```suggestion
    | fullscreen [--no-outer-gaps] [on]
    | fullscreen [on] [--no-outer-gaps]
```

2024-09-01 14:37 UTC, closed without merging

2024-09-01 14:38 UTC, nikitabobko commented
Thanks!

Merged with the following patch:
```diff
diff --git a/Sources/AppBundle/command/FullscreenCommand.swift b/Sources/AppBundle/command/FullscreenCommand.swift
index 6a758b9b..71b70bab 100644
--- a/Sources/AppBundle/command/FullscreenCommand.swift
+++ b/Sources/AppBundle/command/FullscreenCommand.swift
@@ -14,7 +14,7 @@ struct FullscreenCommand: Command {
             case .off: false
             case .toggle: !window.isFullscreen
         }
-        if newState == window.isFullscreen && args.noOuterGaps == window.noOuterGapsInFullscreen {
+        if newState == window.isFullscreen {
             return state.failCmd(msg: newState ? "Already fullscreen" : "Already not fullscreen")
         }
         window.isFullscreen = newState
diff --git a/Sources/Common/cmdArgs/FullscreenCmdArgs.swift b/Sources/Common/cmdArgs/FullscreenCmdArgs.swift
index f865691a..119fee05 100644
--- a/Sources/Common/cmdArgs/FullscreenCmdArgs.swift
+++ b/Sources/Common/cmdArgs/FullscreenCmdArgs.swift
@@ -28,5 +28,5 @@ public struct FullscreenCmdArgs: CmdArgs, RawCmdArgs {
 
 public func parseFullscreenCmdArgs(_ args: [String]) -> ParsedCmd<FullscreenCmdArgs> {
     return parseRawCmdArgs(FullscreenCmdArgs(rawArgs: args), args)
-        .filter("--no-outer-gaps is incompatible with node off") { $0.toggle != .off || $0.noOuterGaps != true }
+        .filter("--no-outer-gaps is incompatible with 'off' argument") { $0.toggle != .off || $0.noOuterGaps != true }
 }
diff --git a/docs/aerospace-fullscreen.adoc b/docs/aerospace-fullscreen.adoc
index 33beda8d..54857b14 100644
--- a/docs/aerospace-fullscreen.adoc
+++ b/docs/aerospace-fullscreen.adoc
@@ -7,9 +7,12 @@ include::util/man-attributes.adoc[]
 
 // =========================================================== Synopsis
 == Synopsis
+
+[verse]
 // tag::synopsis[]
 aerospace fullscreen [-h|--help] [--no-outer-gaps] [on]
 aerospace fullscreen [-h|--help] off
+
 // end::synopsis[]
 
 // =========================================================== Description

```