Draft: Add `--count` flags to `list-*` commands
nikitabobko/AeroSpace pull request #533
Opened 2024-09-25 08:40 UTC by Henkru

This PR adds the `--count` option to the `list-*` commands which outputs the number of filtered items (e.g. windows). This flag is mutually exclusive with the `--format` option.

Example usage:
```bash
$ aerospace list-windows --workspace focused --count
3
```

This is draft PR since the `--count` is currently added only for the `list-windows` command. Before I'll update the other commands, @nikitabobko, does this look a correct approach? I'm still figuring out the code base.

2024-09-25 19:53 UTC, nikitabobko requested changes
Thanks!

The main concern I have is using `ConflictingOptionType` instead of `Set<String>`

2024-09-25 19:53 UTC, nikitabobko commented on Sources/Common/cmdArgs/parseCmdArgs.swift
> +public enum ConflictingOptionType {
Why can't `Set<String>` be used instead of a custom `ConflictingOptionType` type?

2024-09-25 19:53 UTC, nikitabobko commented on Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
> +        conflictingOptions: [
Since you decided to go the "hard way" and implement `conflictingOptions` capability in the parser (which will make it easier to add conflicting options in the future, so thank you!) instead of using `.filter` on `ParsedCmd` inside the `parseRawListWindowsCmdArgs`, it makes sense to migrate a conflict of `--all`, `--focused` and `--workspace`/`--monitor` to `conflictingOptions` mechanism that you introduce

2024-09-25 19:53 UTC, nikitabobko commented on Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
> +        conflictingOptions: [
Also: conflict of options in `list-workspaces`

2024-09-25 20:03 UTC, nikitabobko commented
You also probably need ot update these lines:
```diff
diff --git a/Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift b/Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
index 044d6c26..d0e13ce4 100644
--- a/Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
+++ b/Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
@@ -57,14 +57,14 @@ public func parseRawListWindowsCmdArgs(_ args: [String]) -> ParsedCmd<ListWindow
             }
         }
         .filter("--all conflicts with \"filtering\" flags. Please use '--monitor all'") { raw in
-            !raw.all || raw == ListWindowsCmdArgs(rawArgs: .init([]), all: true, format: raw.format)
+            !raw.all || raw == ListWindowsCmdArgs(rawArgs: .init([]), all: true, format: raw.format, outputOnlyCount: raw.outputOnlyCount)
         }
         .filter("--focused conflicts with \"filtering\" flags") { raw in
-            !raw.focused || raw == ListWindowsCmdArgs(rawArgs: .init(args), focused: true, format: raw.format)
+            !raw.focused || raw == ListWindowsCmdArgs(rawArgs: .init(args), focused: true, format: raw.format, outputOnlyCount: raw.outputOnlyCount)
         }
         .map { raw in
             // Normalize alias
-            raw.all ? ListWindowsCmdArgs(rawArgs: .init(args), monitors: [.all], format: raw.format) : raw
+            raw.all ? ListWindowsCmdArgs(rawArgs: .init(args), monitors: [.all], format: raw.format, outputOnlyCount: raw.outputOnlyCount) : raw
         }
 }
```

2024-09-25 20:05 UTC, Henkru commented on Sources/Common/cmdArgs/parseCmdArgs.swift
> +public enum ConflictingOptionType {
It’s a valid point. I was thinking could there be cases where "mutually exclusive options" aren't enough, and you may need more complex logic to handle those scenarios.

2024-09-25 20:06 UTC, Henkru commented on Sources/Common/cmdArgs/parseCmdArgs.swift
> +public enum ConflictingOptionType {
However, the Set is enough for now. So, I'll remove that enum.

2024-09-25 20:12 UTC, Henkru commented on Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
> +        conflictingOptions: [
I was thinking migrating those into the new mechanism as well. However, that requires a little bit more since one of those flags (`--all`, `--focused`, ...) must be presented, and `conflictingOptions` does not handle that.

Should that be a separate PR?

2024-09-25 20:19 UTC, nikitabobko commented on Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
> +        conflictingOptions: [
> However, that requires a little bit more since one of those flags (--all, --focused, ...) must be presented

You can check it with `.filter`

2024-09-25 20:22 UTC, nikitabobko commented on Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
> +        conflictingOptions: [
> Should that be a separate PR?

Doesn't matter, but I'd prefer to have it in a single PR.

In general, I don't care about splitting code into different PRs. What matters is to split the code in separate commits.

2024-09-26 20:06 UTC, closed without merging

2024-09-26 20:07 UTC, nikitabobko commented
Thanks!

Merged with the following patch squashed to your appropriate commits:

```diff
diff --git a/Sources/AppBundleTests/command/ListWindowsTest.swift b/Sources/AppBundleTests/command/ListWindowsTest.swift
index cfa090e2..e739c1af 100644
--- a/Sources/AppBundleTests/command/ListWindowsTest.swift
+++ b/Sources/AppBundleTests/command/ListWindowsTest.swift
@@ -14,10 +14,10 @@ final class ListWindowsTest: XCTestCase {
         assertEquals(parseCommand("list-windows --all --count --format %{window-title}").errorOrNil, "ERROR: Conflicting options: --count, --format")
         assertEquals(
             parseCommand("list-windows --all --focused --monitor mouse").errorOrNil,
-            "ERROR: Conflicting options: --all, --focused, --monitor")
+            "ERROR: Conflicting options: --all, --focused")
         assertEquals(
             parseCommand("list-windows --all --focused --monitor mouse --workspace focused").errorOrNil,
-            "ERROR: Conflicting options: --all, --focused, --monitor, --workspace")
+            "ERROR: Conflicting options: --all, --focused, --workspace")
         assertEquals(
             parseCommand("list-windows --all --workspace focused").errorOrNil,
             "ERROR: Conflicting options: --all, --workspace")
diff --git a/Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift b/Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
index abf81607..ac5befda 100644
--- a/Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
+++ b/Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift
@@ -22,7 +22,8 @@ public struct ListWindowsCmdArgs: CmdArgs {
         ],
         arguments: [],
         conflictingOptions: [
-            ["--all", "--focused", "--workspace", "--monitor"],
+            ["--all", "--focused", "--workspace"],
+            ["--all", "--focused", "--monitor"],
             ["--format", "--count"],
         ]
     )
@@ -58,7 +59,7 @@ public func parseRawListWindowsCmdArgs(_ args: [String]) -> ParsedCmd<ListWindow
         }
         .map { raw in
             // Normalize alias
-            raw.all ? ListWindowsCmdArgs(rawArgs: .init(args), monitors: [.all], format: raw.format) : raw
+            raw.all ? ListWindowsCmdArgs(rawArgs: .init(args), monitors: [.all], format: raw.format, outputOnlyCount: raw.outputOnlyCount) : raw
         }
 }
 
diff --git a/Sources/Common/cmdArgs/parseSpecificCmdArgs.swift b/Sources/Common/cmdArgs/parseSpecificCmdArgs.swift
index dde0925c..d2f58065 100644
--- a/Sources/Common/cmdArgs/parseSpecificCmdArgs.swift
+++ b/Sources/Common/cmdArgs/parseSpecificCmdArgs.swift
@@ -39,6 +39,7 @@ public func parseSpecificCmdArgs<T: CmdArgs>(_ raw: T, _ args: [String]) -> Pars
         let mutualOptions = conflictSet.intersection(options)
         if mutualOptions.count > 1 {
             errors.append("Conflicting options: \(mutualOptions.sorted().joined(separator: ", "))")
+            break
         }
     }
 
diff --git a/grammar/commands-bnf-grammar.txt b/grammar/commands-bnf-grammar.txt
index a688e519..e4f6de71 100644
--- a/grammar/commands-bnf-grammar.txt
+++ b/grammar/commands-bnf-grammar.txt
@@ -82,13 +82,13 @@ aerospace -h;
 
     | list-monitors [--focused [no] | --mouse [no] | --format <output_format> | --count]...
 
-    | list-windows [<list_windows_filter_flag> | (--format <output_format>|--count)]...
-    | list-windows [--format <output_format>|--count]... --all [--format <output_format>|--count]...
-    | list-windows [--format <output_format>|--count]... --focused [--format <output_format>|--count]...
+    | list-windows [<list_windows_filter_flag> | --format <output_format> | --count]...
+    | list-windows [--format <output_format>|--count] --all [--format <output_format>|--count]
+    | list-windows [--format <output_format>|--count] --focused [--format <output_format>|--count]
 
-    | list-workspaces [<list_workspaces1_flag> | (--format <output_format>|--count)]... --monitor <monitor_id>... [<list_workspaces1_flag> | (--format <output_format>|--count)]...
-    | list-workspaces [--format <output_format>|--count]... --all [--format <output_format>|--count]...
-    | list-workspaces [--format <output_format>|--count]... --focused [--format <output_format>|--count]...
+    | list-workspaces [<list_workspaces1_flag>]... --monitor <monitor_id>... [<list_workspaces1_flag>]...
+    | list-workspaces [--format <output_format>|--count] --all [--format <output_format>|--count]
+    | list-workspaces [--format <output_format>|--count] --focused [--format <output_format>|--count]
     ;
 
 <window_id> ::= {{{ aerospace list-windows --all --format '%{window-id}%{right-padding}%{tab}%{app-name}%{right-padding} | %{window-title}' }}};
@@ -98,7 +98,7 @@ aerospace -h;
 <number> ::= {{{ true }}};
 <monitor_pattern> ::= {{{ true }}};
 
-<list_workspaces1_flag> ::= --visible [no] | --empty [no] | --format <output_format>;
+<list_workspaces1_flag> ::= --visible [no] | --empty [no] | --format <output_format> | --format <output_format> | --count;
 
 <focus_flag> ::= --boundaries <boundary>|--boundaries-action <boundaries_action>|--ignore-floating;
 <boundaries_action> ::= stop|wrap-around-the-workspace|wrap-around-all-monitors;
```

2024-09-26 20:07 UTC, nikitabobko commented on grammar/commands-bnf-grammar.txt
> +    | list-windows [--format <output_format>|--count] --focused [--format <output_format>|--count]
That's a mistake. The flags are incompatible