Goodness: Alfred Workflow
nikitabobko/AeroSpace pull request #554
Opened 2024-10-02 15:06 UTC by yuriteixeira

Alfred Workflow added.

2024-10-11 22:10 UTC, nikitabobko requested changes
Thanks!

1. Please specify the license in your git repo
2. Please specify how to build `.alfredworkflow` file from sources
3. In goodness.adoc, please mention that it's a third party extension (like it's done for raycast)
4. I want goodness.adoc page contain something that keeps the quality bar. Will you be willing to use `--json` to make your script more reliable? #577 (Once `--json` is implemented)

I'm curious why did you choose to focus between windows on the currently visible workspaces. Is it because alfread already allows to switch between all windows? 

Alternatively, You could also choose to switch between windows on the focused workspaces (the difference between focused workspace and visible workspaces is that, in multi-monitor setup, you have only one focused workspace, but as many visible as many monitors you have)

2024-10-20 20:03 UTC, nikitabobko commented
Closing due to inactivity. Feel free to reopen PR, once you fix the comments

2024-10-20 20:03 UTC, closed without merging

2024-10-24 12:23 UTC, yuriteixeira commented on docs/goodness.adoc
> +[alfred,workflow,automation]
Hello 👋 (and sorry for the delay). 

I copied/pasted an entry from another tool and those looked like tags or something, I can see if missed something.

2024-10-24 12:32 UTC, yuriteixeira commented
> Thanks!
> 
> 1. Please specify the license in your git repo

Sure, will do.

> 2. Please specify how to build `.alfredworkflow` file from sources

Afaik, you need to do it using the Alfred UI

![Screenshot 2024-10-24 at 09 28 38](https://github.com/user-attachments/assets/c2630845-3b73-4063-aa94-de72673d35d3)

> 3. In goodness.adoc, please mention that it's a third party extension (like it's done for raycast)

Sure, will do. 

> 4. I want goodness.adoc page contain something that keeps the quality bar. Will you be willing to use `--json` to make your script more reliable? [Add `--json` flag to all query commands #577](https://github.com/nikitabobko/AeroSpace/issues/577) (Once `--json` is implemented)

Sure! But just to clarify: did I miss it or wasn't it implemented?

> I'm curious why did you choose to focus between windows on the currently visible workspaces. Is it because alfread already allows to switch between all windows?
> 

Out of the box (without any 3rd party workflows), Alfred allows to switch between apps, but not windows.

> Alternatively, You could also choose to switch between windows on the focused workspaces (the difference between focused workspace and visible workspaces is that, in multi-monitor setup, you have only one focused workspace, but as many visible as many monitors you have)

The intention of my workflo was to allow the user to list all visible windows (amongst all visible workspaces).

2024-10-24 12:33 UTC, yuriteixeira commented
Btw, it doesn't seem that I have permissions to re-open the PR. Maybe because I didn't push any changes? Anyways, I can ping the admin and ask them to re-open later.