feat: add smart-opposite resize option
nikitabobko/AeroSpace pull request #742
Opened 2024-11-22 15:30 UTC by wesbos

Fixes https://github.com/nikitabobko/AeroSpace/issues/741

I've never worked on a swift app, but it seems like a small add so hopefully this is OK.

2024-11-22 15:39 UTC, nikitabobko requested changes
Please ping me back when you fix the CI

2024-11-22 15:39 UTC, nikitabobko commented on Sources/Common/cmdArgs/impl/ResizeCmdArgs.swift
> +        case width, height, smart, smartOpposite
```suggestion
        case width, height, smart
        case smartOpposite = "smart-opposite"
```

2024-11-22 15:39 UTC, nikitabobko commented on Sources/AppBundleTests/command/ResizeCommandTest.swift
> +        testParseCommandSucc("resize smartopposite 10", ResizeCmdArgs(rawArgs: [], dimension: .smartOpposite, units: .set(10)))
```suggestion
        testParseCommandSucc("resize smart-opposite 10", ResizeCmdArgs(rawArgs: [], dimension: .smartOpposite, units: .set(10)))
```

2024-11-22 15:39 UTC, nikitabobko commented on Sources/AppBundle/command/impl/ResizeCommand.swift
> +                orientation = parent.orientation == .h ? .v : .h
```suggestion
                orientation = parent.orientation.opposite
```

2024-11-22 15:45 UTC, nikitabobko commented
You also need to update this line https://github.com/nikitabobko/AeroSpace/pull/742/files#diff-7a3999a307e560d8f439d95603d6b511bfaefe93607e2e0494505be04af95c0cR12

2024-11-22 19:15 UTC, wesbos commented
@nikitabobko Thanks for your help on this - have the CI passing now

2024-11-23 12:48 UTC, closed without merging

2024-11-23 12:48 UTC, nikitabobko commented
Thanks, merged with the following patch:
```diff
diff --git a/Sources/AppBundle/command/impl/ResizeCommand.swift b/Sources/AppBundle/command/impl/ResizeCommand.swift
index 0bd64498..cd7e5905 100644
--- a/Sources/AppBundle/command/impl/ResizeCommand.swift
+++ b/Sources/AppBundle/command/impl/ResizeCommand.swift
@@ -32,10 +32,11 @@ struct ResizeCommand: Command { // todo cover with tests
                 parent = first.parent as! TilingContainer
                 orientation = parent.orientation
             case .smartOpposite:
-                guard let first = candidates.first else { return false }
+                guard let _orientation = (candidates.first?.parent as? TilingContainer)?.orientation.opposite else { return false }
+                orientation = _orientation
+                guard let first = candidates.first(where: { ($0.parent as! TilingContainer).orientation == orientation }) else { return false }
                 node = first
                 parent = first.parent as! TilingContainer
-                orientation = parent.orientation.opposite
         }
         let diff: CGFloat = switch args.units.val {
             case .set(let unit): CGFloat(unit) - node.getWeight(orientation)
```

otherwise the code crashes.

Please next time always run your code before submitting it, even if it looks trivial